version: 2
jobs:
  build:
    docker: # See https://docs.docker.com/get-started/#docker-concepts if you are new to Docker.
      - image: circleci/node:8.11.3
      - image: mongo:4.0.0
    steps:
      - checkout
      - run: "npm install"
      - run: 
          command: "node ./server/server.js"
          background: true
      - run: "npm test"
