BEGIN;
\c comments
-- \i '/Users/Steven/Comments/postGres/projectData/project1Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project2Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project3Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project4Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project5Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project6Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project7Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project8Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project9Insert.sql'
-- \i '/Users/Steven/Comments/postGres/projectData/project10Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments1Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments2Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments3Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments4Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments5Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments6Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments7Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments8Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments9Insert.sql'
\i '/Users/Steven/Comments/postGres/commentData/comments10Insert.sql'
COMMIT;